import React, { useEffect, useRef, useState } from 'react';
import { Camera, Loader2, RotateCcw, VideoOff } from 'lucide-react';

export default function ScannerCameraPanel({ session, videoRef, overlayCanvasRef, captureCanvasRef, isCameraActive, isPaused, statusText, statusColor, onStartCamera, onStopCamera, onTogglePause, onReopenSession }) {
  // The camera only starts from the single button in the centre of the feed.
  const [starting, setStarting] = useState(false);
  const mountedRef = useRef(true);
  useEffect(() => () => { mountedRef.current = false; }, []);
  const handleStart = async () => {
    if (starting) return;
    setStarting(true);
    try { await onStartCamera?.(); } finally { if (mountedRef.current) setStarting(false); }
  };
  const isClosed = session?.status === 'closed';
  return <div className="card camera-card" style={{ display: 'flex', flexDirection: 'column', overflow: 'hidden' }}><div className="card-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><Camera size={16} /> Live Camera Feed</span><span className="badge badge-outline" role="status" aria-live="polite"><span style={{ width: '7px', height: '7px', borderRadius: '50%', background: statusColor, display: 'inline-block', marginRight: '6px' }} />{statusText}</span></div><div style={{ position: 'relative', minHeight: '440px', background: '#090d16', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><video ref={videoRef} autoPlay playsInline muted style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover', transform: 'scaleX(-1)', display: isCameraActive ? 'block' : 'none' }} /><canvas ref={overlayCanvasRef} style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', pointerEvents: 'none', display: isCameraActive ? 'block' : 'none' }} /><canvas ref={captureCanvasRef} style={{ display: 'none' }} />{!isCameraActive && <div style={{ color: '#f1f5f9', textAlign: 'center' }}>{session?.status === 'closed' ? <RotateCcw size={28} /> : <VideoOff size={28} />}<div>{session?.status === 'closed' ? 'Attendance Session Closed' : 'Camera Feed Offline'}</div><button type="button" className="btn btn-primary" style={{ marginTop: '14px', display: 'inline-flex', alignItems: 'center', gap: '8px' }} onClick={isClosed ? onReopenSession : handleStart} disabled={starting} data-self-loading={isClosed ? undefined : ''} aria-busy={starting || undefined}>{isClosed ? <>Reopen &amp; Start Attendance</> : starting ? <><Loader2 size={16} className="spin" aria-hidden="true" /> Starting…</> : <>Start Camera</>}</button></div>}</div><div className="card-footer" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>{isCameraActive && <div style={{ display: 'flex', gap: '8px' }}><button type="button" className="btn btn-outline" onClick={onStopCamera}>Stop Camera</button><button type="button" className="btn btn-outline" onClick={onTogglePause}>{isPaused ? 'Resume Recognition' : 'Pause Recognition'}</button></div>}<span className="text-muted">Real-time face tracking • Auto-verifies</span></div></div>;
}
