# Generated by Django 6.1.1 on 2026-09-30 07:51

import accounts.validators
import attendance_fr.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('college', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive records are temporarily closed and hidden from new activity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'academic_programs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('year_level', models.PositiveSmallIntegerField(default=1)),
                # Created with the table (not a later AddField): TiDB rejects
                # ALTER TABLE ... ADD COLUMN with a UNIQUE key (error 8200).
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(help_text='e.g. 2025-2026', max_length=20)),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('summer', 'Summer')], default='1st', max_length=10)),
            ],
            options={
                'db_table': 'academic_terms',
                'ordering': ['-school_year', 'semester'],
                'constraints': [models.UniqueConstraint(fields=('school_year', 'semester'), name='unique_academic_term')],
            },
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive records are temporarily closed and hidden from new activity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sections', to='core.academicterm')),
            ],
            options={
                'db_table': 'academic_class_sections',
                'ordering': ['template__name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=50)),
                ('effective_from', models.DateField(blank=True, help_text='First date this schedule is active', null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Last date this schedule is active', null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.classsection')),
            ],
            options={
                'db_table': 'academic_class_schedules',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, help_text='Academic title, e.g. Prof., Dr., Engr.', max_length=50)),
                ('position', models.CharField(blank=True, help_text='Rank, e.g. Assistant Professor', max_length=100)),
                ('employment_status', models.CharField(blank=True, default='Regular', max_length=50)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('office_location', models.CharField(blank=True, max_length=150)),
                ('consultation_hours', models.TextField(blank=True)),
                ('education_background', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor',
                'db_table': 'instructors',
            },
        ),
        migrations.AddField(
            model_name='classsection',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Section-level instructor; used only when no subject in the section has its own instructor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sections', to='core.instructor'),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.classschedule')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_started', to='core.instructor')),
            ],
            options={
                'db_table': 'attendance_sessions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.program')),
            ],
            options={
                'db_table': 'academic_courses',
                'ordering': ['program__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_level', models.PositiveSmallIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive records are temporarily closed and hidden from new activity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_templates', to='core.course')),
            ],
            options={
                'db_table': 'academic_section_templates',
                'ordering': ['course__program__code', 'course__code', 'year_level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='classsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sections', to='core.sectiontemplate'),
        ),
        migrations.CreateModel(
            name='SessionReopenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('reopened_at', models.DateTimeField(auto_now_add=True)),
                ('reopened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_reopens', to='core.instructor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopen_history', to='core.attendancesession')),
            ],
            options={
                'db_table': 'attendance_session_reopen_logs',
                'ordering': ['-reopened_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentBiometric',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='biometric', serialize=False, to='core.student')),
                ('face_encoding', models.TextField(help_text='JSON list of 128 floats')),
                ('face_image', models.ImageField(blank=True, null=True, storage=attendance_fr.storage.get_face_storage, upload_to='face_images/', validators=[accounts.validators.validate_image_upload])),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Biometric',
                'db_table': 'student_biometrics',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.course'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='absent', max_length=10)),
                ('recognized_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['student__user__profile__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('units', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive records are temporarily closed and hidden from new activity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.instructor')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.classsection')),
            ],
            options={
                'db_table': 'academic_subjects',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.classsection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
                ('subject', models.ForeignKey(blank=True, help_text='Leave empty for a regular block student; set for an irregular student.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.subject')),
            ],
            options={
                'db_table': 'academic_enrollments',
            },
        ),
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.subject'),
        ),
        migrations.CreateModel(
            name='ClassScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=3)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.classschedule')),
            ],
            options={
                'db_table': 'academic_class_schedule_days',
                'indexes': [models.Index(fields=['day'], name='schedule_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'day'), name='unique_day_per_schedule')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('schedule', 'date'), name='one_session_per_meeting'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('program', 'code'), name='unique_course_per_program'),
        ),
        migrations.AddIndex(
            model_name='sectiontemplate',
            index=models.Index(fields=['course', 'year_level'], name='template_course_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='sectiontemplate',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='unique_section_name_per_course'),
        ),
        migrations.AddConstraint(
            model_name='classsection',
            constraint=models.UniqueConstraint(fields=('template', 'term'), name='unique_section_per_term'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course', 'year_level'], name='student_course_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='one_record_per_student_session'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['section', 'subject'], name='enrollment_section_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'section', 'subject'), name='unique_enrollment'),
        ),
    ]
