# Generated by Django 6.1.1 on 2026-10-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_attendance_record_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='late_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='start_mode',
            field=models.CharField(choices=[('on_time', 'On time'), ('present', 'Started late, students present'), ('late', 'Started late, students late')], default='on_time', max_length=10),
        ),
    ]
