import { resolveMediaUrl } from '../../api';
import React, { useState } from 'react';
import { AlertTriangle, BarChart2, BookOpen,  CheckCircle, ClipboardList, Clock, GraduationCap } from 'lucide-react';
import StudentAttendanceCalendarModal from '../StudentAttendanceCalendarModal';
import Avatar from '../shared/Avatar';

export default function DashboardStudent({ user, studentOverview, onNavigate }) {
  const [selectedCalendarSection, setSelectedCalendarSection] = useState(null);
  const student = studentOverview?.student || user?.student_profile;
  const fullName = student?.full_name || `${user?.first_name || ''} ${user?.last_name || ''}`.trim() || user?.username;
  const studentStats = studentOverview?.overall_stats || { rate: 0, total_sessions: 0, present: 0, late: 0, absent: 0, excused: 0 };
  const enrolledCards = studentOverview?.enrolled_cards || [];
  const recentLogs = studentOverview?.recent_records || [];

  return (
    <div className="page-content">
      <div className="grid-2 mb-3">
        <div className="card"><div className="card-header"><span className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><GraduationCap size={16} /> My Profile</span></div><div className="card-body"><div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '16px' }}><Avatar src={resolveMediaUrl(student?.profile_image || user?.profile_image)} name={fullName} size={60} alt="Profile photo" /><div><div className="font-bold" style={{ fontSize: '18px' }}>{fullName}</div><div className="text-muted">Student ID: <strong>{student?.student_id || '2024-00001'}</strong></div><div className="text-muted">Login: {user?.username}</div><div className="text-muted">{student?.course || 'BSIT'} &mdash; Year {student?.year_level || 1}</div></div></div>{student?.is_face_enrolled ? <div className="alert alert-success" style={{ marginBottom: 0, display: 'flex', alignItems: 'center', gap: '8px' }}><CheckCircle size={16} /><span>Biometric profile verified {student.face_enrolled_at ? `(Enrolled on ${new Date(student.face_enrolled_at).toLocaleDateString()})` : ''}</span></div> : <div className="alert alert-warning" style={{ marginBottom: 0, display: 'flex', alignItems: 'center', gap: '8px' }}><AlertTriangle size={16} /><span>Biometric profile not registered &mdash; contact your administrator for face enrollment.</span></div>}</div></div>
        <div className="card"><div className="card-header"><span className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><BarChart2 size={16} /> Attendance Summary</span></div><div className="card-body"><div className="stats-grid" style={{ gridTemplateColumns: 'repeat(2, 1fr)', marginBottom: '12px' }}><div className="stat-card green" style={{ padding: '12px' }}><div className="stat-info"><div className="value" style={{ fontSize: '24px' }}>{studentStats.rate}%</div><div className="label">Overall rate</div></div></div><div className="stat-card blue" style={{ padding: '12px' }}><div className="stat-info"><div className="value" style={{ fontSize: '24px' }}>{studentStats.total_sessions}</div><div className="label">Sessions logged</div></div></div></div><div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px', fontSize: '12px' }}><span className="badge badge-success">Present: {studentStats.present}</span><span className="badge badge-warning">Late: {studentStats.late}</span><span className="badge badge-danger">Absent: {studentStats.absent}</span><span className="badge badge-info">Excused: {studentStats.excused}</span></div></div></div>
      </div>

      <div className="card mb-3"><div className="card-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><span className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><BookOpen size={16} /> Attendance by Subject / Section</span><span className="text-muted" style={{ fontSize: '12px' }}>{enrolledCards.length} enrolled class(es)</span></div><div className="table-container" style={{ border: 'none' }}><table><thead><tr><th>Subject</th><th>Section</th><th>Sessions</th><th>Present</th><th>Late</th><th>Absent</th><th>Rate</th><th>Last Class</th><th style={{ textAlign: 'right' }}>Calendar</th></tr></thead><tbody>{enrolledCards.length === 0 ? <tr><td colSpan="9" className="text-center text-muted" style={{ padding: '30px' }}>You are not enrolled in any sections yet.</td></tr> : enrolledCards.map((card) => <tr key={card.section_id}><td><span className="badge badge-accent">{card.subject_code}</span><div className="text-muted" style={{ fontSize: '11px', marginTop: '2px' }}>{card.subject_name}</div></td><td><strong>{card.section_name}</strong></td><td>{card.total_sessions}</td><td>{card.present_count}</td><td>{card.late_count}</td><td>{card.absent_count}</td><td>{card.rate !== null && card.rate !== undefined ? <strong>{card.rate}%</strong> : <span className="text-muted">—</span>}</td><td className="text-muted" style={{ fontSize: '12px' }}>{card.last_date ? <span>{card.last_date} {card.last_status === 'present' && <span className="badge badge-success" style={{ marginLeft: '4px' }}>P</span>}{card.last_status === 'late' && <span className="badge badge-warning" style={{ marginLeft: '4px' }}>L</span>}{card.last_status === 'absent' && <span className="badge badge-danger" style={{ marginLeft: '4px' }}>A</span>}</span> : '—'}</td><td style={{ textAlign: 'right' }}><button type="button" className="btn btn-outline btn-sm" onClick={() => setSelectedCalendarSection(card)} style={{ display: 'inline-flex', alignItems: 'center', gap: '4px' }}><span>View</span></button></td></tr>)}</tbody></table></div></div>

      <div className="card"><div className="card-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><span className="card-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><ClipboardList size={16} /> Recent Attendance</span><button type="button" className="btn btn-outline btn-sm" onClick={() => onNavigate('session_logs')}>View All</button></div><div className="table-container" style={{ border: 'none' }}><table><thead><tr><th>Date</th><th>Subject</th><th>Section</th><th>Status</th><th>Time In</th></tr></thead><tbody>{recentLogs.length === 0 ? <tr><td colSpan="5" className="text-center text-muted" style={{ padding: '30px' }}>No attendance records yet. Records appear after your instructor takes class attendance.</td></tr> : recentLogs.map((log) => <tr key={log.id}><td>{log.date}</td><td><span className="badge badge-accent">{log.subject_code}</span></td><td>{log.section_name}</td><td>{log.status === 'present' ? <span className="badge badge-success"><CheckCircle size={12} /> Present</span> : log.status === 'late' ? <span className="badge badge-warning"><Clock size={12} /> Late</span> : <span className="badge badge-danger"><AlertTriangle size={12} /> Absent</span>}</td><td className="text-muted">{log.time}</td></tr>)}</tbody></table></div></div>

      {selectedCalendarSection && <StudentAttendanceCalendarModal isOpen={Boolean(selectedCalendarSection)} onClose={() => setSelectedCalendarSection(null)} sectionId={selectedCalendarSection.section_id} initialTitle={selectedCalendarSection.title} initialSubject={selectedCalendarSection.subject_name} initialInstructor={selectedCalendarSection.instructor_name} />}
    </div>
  );
}
