import React from 'react';
import { UserPlus, X } from 'lucide-react';
import PasswordInput from '../shared/PasswordInput';
import { ModalBackdrop } from '../../ui';

export default function RegisterStudentModal({ isOpen, form, setForm, error, submitting, onClose, onSubmit }) {
  if (!isOpen) return null;
  const update = (key, value) => setForm((previous) => ({ ...previous, [key]: value }));
  return <ModalBackdrop onClose={onClose} busy={submitting} role="dialog" aria-modal="true" style={{ alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '16px' }}><div className="modal-card" style={{ maxWidth: '560px', width: '100%' }}><div className="modal-header"><div><h3 className="modal-title"><UserPlus size={18} /> Register Student</h3><div className="modal-subtitle">Enroll a new student into the attendance system</div></div><button type="button" onClick={onClose} className="modal-close-btn"><X size={18} /></button></div><form onSubmit={onSubmit}><div className="modal-body" style={{ padding: '20px' }}>{error && <div className="alert alert-danger" style={{ marginBottom: '14px' }}>{error}</div>}<div className="grid-2"><Field label="Student ID Number *"><input className="form-control" required value={form.student_id} onChange={(event) => update('student_id', event.target.value)} /></Field><Field label="First Name *"><input className="form-control" required value={form.first_name} onChange={(event) => update('first_name', event.target.value)} /></Field><Field label="Last Name *"><input className="form-control" required value={form.last_name} onChange={(event) => update('last_name', event.target.value)} /></Field><Field label="Email Address"><input type="email" className="form-control" value={form.email} onChange={(event) => update('email', event.target.value)} /></Field><Field label="Degree Course *"><input className="form-control" required placeholder="e.g. BSIT" value={form.course} onChange={(event) => update('course', event.target.value)} /></Field><Field label="Year Level *"><select className="form-select" required value={form.year_level} onChange={(event) => update('year_level', event.target.value)}><option value="">Select Year Level</option><option value={1}>1st Year</option><option value={2}>2nd Year</option><option value={3}>3rd Year</option><option value={4}>4th Year</option></select></Field><div style={{ gridColumn: '1 / -1' }}><PasswordInput id="register-student-password" floatingLabel="Account Password *" required value={form.password} onChange={(event) => update('password', event.target.value)} showStrength /><small className="text-muted">Each student needs their own strong password. There is no default password.</small></div></div></div><div className="modal-footer"><button type="button" className="btn btn-outline" data-modal-close onClick={onClose}>Cancel</button><button type="submit" className="btn btn-primary" disabled={submitting}>{submitting ? 'Registering...' : 'Register Student'}</button></div></form></div></ModalBackdrop>;
}
function Field({ label, children }) { return <div className="form-group"><label className="form-label">{label}</label>{children}</div>; }
