import React, { useEffect, useMemo, useState } from 'react';
import { BriefcaseBusiness, Building2, CalendarDays, CheckCircle2, GraduationCap, IdCard, Mail, MapPin,  UserRound } from 'lucide-react';
import { Api } from '../api';
import Toast from '../components/shared/Toast';
import PhoneInput from '../components/shared/PhoneInput';
import { getPhPhoneValidationMessage } from '../utils/validation';

const teacherFields = ['first_name', 'last_name', 'email', 'phone', 'title', 'specialization', 'contact_number', 'office_location', 'consultation_hours', 'education_background', 'certifications'];

export default function ProfileView({ user, onUserUpdated, onSetHeaderInfo }) {
  const [editing, setEditing] = useState(false); const [submitting, setSubmitting] = useState(false); const [success, setSuccess] = useState(''); const [error, setError] = useState('');
  const initial = useMemo(() => buildForm(user), [user]); const [form, setForm] = useState(initial);
  useEffect(() => setForm(initial), [initial]);
  useEffect(() => { onSetHeaderInfo?.({ title: 'My Profile', subtitle: 'Your professional identity, contact information, and account details.', headerActions: !editing ? <button type="button" className="btn btn-primary" onClick={() => setEditing(true)}>Edit profile</button> : null }); }, [editing, onSetHeaderInfo]);
  const instructor = user?.instructor_profile || {}; const fullName = [instructor.title, user?.first_name, user?.last_name].filter(Boolean).join(' ') || user?.username || 'Faculty member';
  const save = async (event) => { event.preventDefault(); if (form.phone) { const issue = getPhPhoneValidationMessage(form.phone); if (issue) { setError(issue); return; } } try { setSubmitting(true); setError(''); const payload = Object.fromEntries(teacherFields.map((field) => [field, form[field] ?? ''])); const updated = await Api.updateProfile(payload); onUserUpdated?.(updated); setSuccess('Profile updated successfully.'); setEditing(false); } catch (saveError) { setError(saveError.message || 'Unable to update profile.'); } finally { setSubmitting(false); } };
  // In view mode show a neutral 'Not provided' instead of input examples.
  const ph = (example) => (editing ? example : 'Not provided');
  const set = (field) => (event) => setForm((current) => ({ ...current, [field]: event.target.value }));
  return <div className="page-content profile-page"><Toast message={success} type="success" onClose={() => setSuccess('')} /><Toast message={error} type="error" onClose={() => setError('')} />
    <section className="profile-hero"><div className="profile-avatar">{(user?.first_name?.[0] || user?.username?.[0] || 'T').toUpperCase()}</div><div className="profile-hero-copy"><span className="badge badge-accent"><BriefcaseBusiness size={13} /> Faculty profile</span><h2>{fullName}</h2><p>{instructor.position || 'Faculty member'} · {instructor.department || 'Department not assigned'}</p><div className="profile-identity-row"><span><IdCard size={14} /> {instructor.faculty_id || 'Faculty ID pending'}</span><span><Mail size={14} /> {user?.email || 'No email set'}</span><span className={`profile-active ${user?.is_active ? '' : 'inactive'}`}><CheckCircle2 size={14} /> {user?.is_active ? 'Active account' : 'Inactive account'}</span></div></div></section>
    <form onSubmit={save} className="profile-layout"><section className="card profile-card profile-contact-card"><ProfileHeading icon={UserRound} title="Personal & contact" note="Information you can update yourself" /><div className="profile-card-body profile-field-grid"><Field label="First name"><input className="form-control" value={form.first_name} onChange={set('first_name')} disabled={!editing} required /></Field><Field label="Last name"><input className="form-control" value={form.last_name} onChange={set('last_name')} disabled={!editing} required /></Field><Field label="Email address" full><input className="form-control" type="email" value={form.email} onChange={set('email')} disabled={!editing} required /></Field><Field label="Mobile number"><PhoneInput value={form.phone} onChange={set('phone')} disabled={!editing} placeholder={ph('e.g. 09123456789')} /></Field><Field label="Faculty contact number"><input className="form-control" value={form.contact_number} onChange={set('contact_number')} disabled={!editing} placeholder={ph('Office or alternate number')} /></Field><Field label="Office location" full><div className="input-with-icon"><MapPin size={15} /><input className="form-control" value={form.office_location} onChange={set('office_location')} disabled={!editing} placeholder={ph('Building, room, or office')} /></div></Field></div></section>
      <section className="card profile-card"><ProfileHeading icon={GraduationCap} title="Professional profile" note="Describe your expertise and availability" /><div className="profile-card-body profile-field-grid"><Field label="Academic title"><input className="form-control" value={form.title} onChange={set('title')} disabled={!editing} placeholder={ph('e.g. Prof., Dr., Engr.')} /></Field><Field label="Specialization"><input className="form-control" value={form.specialization} onChange={set('specialization')} disabled={!editing} placeholder={ph('e.g. Software Engineering')} /></Field><Field label="Consultation hours" full><textarea className="form-control" rows="2" value={form.consultation_hours} onChange={set('consultation_hours')} disabled={!editing} placeholder={ph('e.g. Mon–Wed, 1:00–3:00 PM')} /></Field><Field label="Education background" full><textarea className="form-control" rows="3" value={form.education_background} onChange={set('education_background')} disabled={!editing} placeholder={ph('Degrees and academic background')} /></Field><Field label="Professional certifications" full><textarea className="form-control" rows="3" value={form.certifications} onChange={set('certifications')} disabled={!editing} placeholder={ph('Licenses, certifications, and professional memberships')} /></Field></div></section>
      <section className="card profile-card profile-managed-card"><ProfileHeading icon={Building2} title="Institutional information" note="Managed by the administrator" /><div className="profile-card-body profile-readonly-grid"><Readonly label="Faculty ID" value={instructor.faculty_id} icon={IdCard} /><Readonly label="Department" value={instructor.department} icon={Building2} /><Readonly label="Position / rank" value={instructor.position} icon={BriefcaseBusiness} /><Readonly label="Employment status" value={instructor.employment_status} icon={CheckCircle2} /><Readonly label="Date hired" value={formatDate(instructor.date_hired)} icon={CalendarDays} /><Readonly label="Username" value={user?.username} icon={UserRound} /></div></section>
      {editing && <div className="profile-save-bar"><button type="button" className="btn btn-outline" onClick={() => { setForm(initial); setEditing(false); }}>Cancel</button><button type="submit" className="btn btn-primary" disabled={submitting}>{submitting ? 'Saving…' : 'Save profile'}</button></div>}
    </form></div>;
}
function buildForm(user) { const profile = user?.instructor_profile || {}; return { first_name: user?.first_name || '', last_name: user?.last_name || '', email: user?.email || '', phone: user?.phone || '', title: profile.title || '', specialization: profile.specialization || '', contact_number: profile.contact_number || '', office_location: profile.office_location || '', consultation_hours: profile.consultation_hours || '', education_background: profile.education_background || '', certifications: profile.certifications || '' }; }
function ProfileHeading({ icon: Icon, title, note }) { return <div className="profile-card-heading"><span><Icon size={17} /></span><div><h3>{title}</h3><p>{note}</p></div></div>; }
function Field({ label, full, children }) { return <label className={`form-group ${full ? 'profile-field-full' : ''}`}><span className="form-label">{label}</span>{children}</label>; }
function Readonly({ label, value, icon: Icon }) { return <div className="profile-readonly"><Icon size={15} /><span><small>{label}</small><strong>{value || 'Not provided'}</strong></span></div>; }
function formatDate(value) { return value ? new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }) : ''; }